config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  
  root 'pages#index'

  get '/about-us'     => 'pages#about'
  get '/contact-us'   => 'pages#contact'
  get '/testimonials' => 'pages#testimonials'
  get '/blogs'        => 'blogs#index',       :as => :blogs
  get '/blogs/:id'    => 'blogs#show',        :as => :post
  
  get '/websites/for-real-estate-agents/:page' => 'agents#show', :as => 'agent_page'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, :use => :scoped, :scope => :blog_id
  
  has_many :blog_post_taggings
  has_many :categories, through: :blog_post_taggings
  
  def self.recent
    where("blog_id" => nil).order('published_at DESC').limit(3)
  end

  def thumbnail
    if parsed_content.search('img').first.blank?
      img_url = "/assets/blogging-default.jpg"
    else
      img_url = parsed_content.search('img').first.attributes["src"].value rescue nil
    end
  end

  def excerpt
    parsed_content.css('.excerpt').text
  end

  def plain_text
    @text ||= Nokogiri::HTML(content).text
  end

private

  def parsed_content
    @doc ||= Nokogiri::HTML(content).search('html > body > *')
  end
  
end

app/models/blog_post_tagging.rb
class BlogPostTagging < ActiveRecord::Base
  belongs_to :category
  belongs_to :blog_post
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :scoped, :scope => :blog_id
    
  has_many :blog_post_taggings
  has_many :blog_posts, through: :blog_post_taggings
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:email]
                  
  attr_accessor   :credit_card_number, :cvv
  
  def normalize_street_address
      address = StreetAddress::US.parse("#{self.office_street_address}, #{self.office_city}, NV, #{self.office_zipcode}")
      if address
          return "#{address.number} #{address.prefix.gsub(/[^A-Z]/, '') rescue ''} #{address.street} #{address.street_type.gsub(/[^A-Za-z]/, '') rescue ''} #{address.suffix.gsub(/[^A-Za-z]/, '') rescue ''} #{address.unit_prefix.gsub(/[^A-Za-z]/, '') rescue ''} #{address.unit.gsub(/[^0-9A-Z]/, '') rescue ''}".split.join(" ")
      end
  end
  
  def name
    [self.first_name, self.last_name].compact.join(' ')
  end
  
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  has_one :site, :dependent => :destroy
    
  def create_and_subscribe(customer_hash)
    raise
  end
  
  def subscription
    @subscription ||= Chargify::Subscription.find(subscription_id)
  end
  
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  
  def show
    render template: "agents/#{params[:page]}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @posts = BlogPost.recent
  end
  
  def show
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end
  
  def about
  end
  
  def contact
  end
  
  def testimonials
  end
  
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :authenticate_customer!, except: [:completed]
  
  def company
  end
  
  def domain
  end
  
  def agreement
  end
  
  def site
  end
  
  def completed
  end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def render_breadcrumbs?
    !(params[:action] == 'index' && params[:controller] == 'pages')
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
    :count => resource.errors.count,
    :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" data-uk-scrollspy="{cls:'uk-animation-slide-left', repeat: false, delay:700}">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/agents/cms.html.erb
<%= content_for(:title, "CMS For Real Estate Agents | Agent Formula Real Estate Websites") %>
<h1>Powerful CMS</h1>

app/views/agents/content.html.erb
<%= content_for(:title, "Sticky Content | Agent Formula Real Estate Websites") %>
<div class='content'>
  <div class='uk-container uk-container-center'>
    <h1>Sticky Content</h1>
  </div>
</div>

app/views/agents/crm.html.erb
<%= content_for(:title, "CRM For Real Estate Agents | Agent Formula Real Estate Websites") %>
<div class='content'>
  <div class='uk-container uk-container-center'>
    <h1>CRM Lead Management</h1>
  </div>
</div>

app/views/agents/drip-marketing.html.erb
<%= content_for(:title, "Drip Marketing For Real Estate Agents | Agent Formula Real Estate Websites") %>

<div class='content'>
  <div class='uk-container uk-container-center'>
    <h1>Email Drip Marketing</h1>
  </div>
</div>

app/views/agents/features.html.erb
<%= content_for(:title, "Website Features For Real Estate Agents | Agent Formula Real Estate Websites") %>
<h1>Features</h1>

app/views/agents/idx.html.erb
<%= content_for(:title, "MLS IDX Property Search For Real Estate Agents | Agent Formula Real Estate Websites") %>
<h1>MLS IDX Search</h1> 

app/views/agents/lead-capture.html.erb
<%= content_for(:title, "Lead Capture For Real Estate Agents | Agent Formula Real Estate Websites") %>
<h1>Lead Capture</h1>
<ul>
  <li>Nosy Neighbor</li>
  <li>Relocation Guide</li>
  <li>Investor PowerPoint</li>
  <li>Cashflow Calculator</li>
</ul>

app/views/agents/social-media.html.erb
<%= content_for(:title, "Social Media Publishing For Real Estate Agents | Agent Formula Real Estate Websites") %>
<h1>Easy Social Media Publishing</h1>

app/views/agents/support.html.erb
<%= content_for(:title, "Support | AgentFormula.com") %>

<h1>Support</h1>

app/views/agents/training.html.erb
<%= content_for(:title, "Internet Marketing Training For Real Estate Agents | Agent Formula Real Estate Websites") %>
<h1>Training Classes</h1>

app/views/agents/videos.html.erb
<%= content_for(:title, "HD Videos For Real Estate Agents | AgentFormula Websites") %>
<h1>HD Videos</h1>

app/views/blogs/index.html.erb
<%= content_for(:title, "Blog | AgentFormula.com") %>
<%= content_for(:page_header, 'shared/headers/blog')%>
<%= content_for(:breadcrumb, 'Recent Blog Posts')%>

<div class='tm-block-bg-main uk-margin-large-top'>
  <div class='uk-container uk-container-center'>
    <div class='tm-middle tm-padding-bottom-medium uk-grid' data-uk-grid-match data-uk-grid-margin>
      <div class='tm-main uk-width-medium-1-1'>
        <main class='tm-content'>
          <div class='uk-grid' data-uk-grid-match data-uk-grid-margin>
            <div class='uk-width-medium-1-1'>
              <% @posts.each do |post| %>
              <article id="<%= post.id %>" class='uk-article post status-publish format-standard has-post-thumbnail hentry category-children-health-questions tag-children tag-health tag-patient' data-permalink="<%= post_path(post.id) %>">
                <h2 class='uk-article-title'>
                  <%= link_to post.title, post_path(post.id) %>
                </h2>
                <p class='uk-article-meta tm-meta-border-bot'>
                  By <%= link_to post.author, post_path(post.id) %>.
                  <%#= raise %>
                  <time datetime="<%= post.published_at.strftime("%b %d, %Y %I:%m%p")%>"><%= post.published_at.strftime("%b %d, %Y %I:%m%p")%></time>
                </p>
                <%= link_to post_path(post.id) do %>
                  <%= image_tag(post.thumbnail, width: '150', height: '150', class: 'tm-category-post-thumb') %>
                <% end %>
                <div class='tm-single-article-content uk-margin-bottom'>
                  <%= post.excerpt %>
                </div>
              </article>
              <% end %>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:controller] %>">
  <%= render 'shared/navbar' %>
  <%= render 'shared/lead_topic' %>
  <% if !yield(:page_header).blank? %>
  <%= render yield(:page_header) %>
  <% end %>
  <% if render_breadcrumbs? %>
  <%= render 'shared/breadcrumb_bar' %>
  <% end %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <%= yield(:dynamic_javascripts) %>
</body>
</html>

app/views/pages/about.html.erb
<%= content_for(:title, "About Us | AgentFormula.com") %>
<h1>About Us Page</h1>

app/views/pages/comparison.html.erb
<%= content_for(:title, "Website Compairison | AgentFormula.com") %>
<h1>Compairision</h1>

app/views/pages/contact.html.erb
<%= content_for(:title, "Contact Us | AgentFormula.com") %>
<%#= content_for(:page_header, 'shared/headers/blog')%>

<div class="">
  <div class="tm-section-box ">
    <div class="uk-container uk-container-center">
      <section class="tm-bottom-a uk-grid tm-padding-top-large  tm-padding-bottom-large " data-uk-grid-match="{target:'> div > .uk-panel'}" data-uk-grid-margin="">
        <div class="uk-width-1-1">
          <div class="uk-panel">
            <div class="uk-grid uk-flex uk-flex-top uk-grid-collapse" data-uk-grid-margin="" data-uk-grid-match="">
              <div class="uk-panel uk-width-small-1-1 uk-width-medium-2-3 uk-flex-top uk-margin-large-bottom">
                <!-- Google Map Goes Here -->
                <div id='location-map' class='google-maps-responsive'></div>              
              </div>        
              <div class="uk-panel uk-width-small-1-1 uk-width-medium-1-3 uk-margin-large-bottom">     
                <div class="uk-accordion tm-accordion-plus" data-uk-accordion data-uk-scrollspy="{cls:'uk-animation-slide-bottom', repeat: false, delay:500}">
              
                  <h6 class="uk-accordion-title">
                    <div class="hexagon"><span></span></div>
                    AGENT FORMULA
                  </h6>
                  <div data-wrapper="true" style="height: auto; position: relative;" aria-expanded="true">
                    <div class="uk-accordion-content">
                      8400 W Sahara Ave,<br>
                      Las Vegas, NV 89117<br>
                      <strong>Phone:</strong> (702)-990-0480<br>
                      <strong>Email:</strong> <a href="mailto:sales@agentformula.com">sales@agentformula.com</a><br>
                    </div>
                  </div>
              
                  <h6 class="uk-accordion-title">
                    <div class="hexagon"><span></span></div>
                    Support (Agentcare)
                  </h6>
                  <div data-wrapper="true" style="overflow:hidden;height:0;position:relative;" aria-expanded="false">
                    <div class="uk-accordion-content">
                      8400 W Sahara Ave,<br>
                      Las Vegas, NV 89117<br>
                      <strong>Phone:</strong> (702)-990-0480<br>
                      <strong>Email:</strong> <a href="mailto:agentcare@agentformula.com">agentcare@agentformula.com</a><br>
                    </div>
                  </div>
              
                  <h6 class="uk-accordion-title">
                    <div class="hexagon"><span></span></div>
                    Finance Department
                  </h6>
                  <div data-wrapper="true" style="overflow:hidden;height:0;position:relative;" aria-expanded="false">
                    <div class="uk-accordion-content">
                      Maryann McCabe<br>
                      <strong>Phone:</strong> (702)-990-0480<br>
                      <strong>Email:</strong> <a href="mailto:finance@agentformula.com">finance@agentformula.com</a><br>
                    </div>
                  </div>
                  
                </div>
              </div>  
            </div>
          </div>
        </div>
      </section> 
    </div>
  </div>
</div>

<div class="">
  <div class="tm-section-box tm-block-bg-muted">
    <div class="uk-container uk-container-center">
      <section class="tm-bottom-c uk-grid tm-padding-top-large tm-padding-bottom-medium " data-uk-grid-match="{target:'> div > .uk-panel'}" data-uk-grid-margin>
        <div class="uk-width-1-1">
          <div class="uk-panel tm-touch-form widget_text" data-uk-scrollspy="{cls:'uk-animation-fade', delay:500}">
            <div class="uk-grid" data-uk-grid-margin="">
              <div class="uk-width-1-1 uk-width-medium-1-2">
                <h3 class="uk-panel-title">Get in touch</h3>
              </div>
              <div class="uk-width-1-1 uk-width-medium-1-2">
                <div class="tm-touch-social">
                  <a draggable="false" href="#" class="uk-icon-small uk-icon-hover uk-icon-facebook"></a>
                  <a draggable="false" href="#" class="uk-icon-small uk-icon-hover uk-icon-twitter"></a>
                  <a draggable="false" href="#" class="uk-icon-small uk-icon-hover uk-icon-google-plus"></a>
                  <a draggable="false" href="#" class="uk-icon-small uk-icon-hover uk-icon-linkedin"></a>
                  <a draggable="false" href="#" class="uk-icon-small uk-icon-hover uk-icon-youtube"></a>
                </div>
              </div>
              <div class="uk-width-1-1 uk-grid-margin">
                <p>Need to speak with someone directly, or just have a few questions about Agent Formula? Don't hesitate to contact us.</p>
              </div>
              <div class="uk-width-1-1 uk-grid-margin">
                <div role="form" class="wpcf7" id="wpcf7-f458-o1" lang="en-US" dir="ltr">
                  <div class="screen-reader-response"></div>
                  <form action="/?page_id=27#wpcf7-f458-o1" method="post" class="wpcf7-form" novalidate="novalidate">
                    <div style="display: none;">
                      <input type="hidden" name="_wpcf7" value="458">
                      <input type="hidden" name="_wpcf7_version" value="4.2.2">
                      <input type="hidden" name="_wpcf7_locale" value="en_US">
                      <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f458-o1">
                      <input type="hidden" name="_wpnonce" value="fdb738fa1e">
                    </div>
                    <div class="uk-grid uk-grid-medium" data-uk-grid-margin="">
                      <div class="uk-width-1-1 uk-width-small-1-2 uk-width-medium-2-5 uk-width-large-2-5">
                        <span class="wpcf7-form-control-wrap your-name">
                          <input type="text" name="your-name" value="" size="40" class="tm-touch-name" aria-required="true" aria-invalid="false" placeholder="Name">
                        </span><br>
                        <span class="wpcf7-form-control-wrap your-email">
                          <input type="url" name="your-email" value="" size="40" class="tm-touch-email" aria-required="true" aria-invalid="false" placeholder="Email">
                        </span><br>
                        <span class="wpcf7-form-control-wrap your-subject">
                          <input type="text" name="your-subject" value="" size="40" class="tm-touch-subject" aria-required="true" aria-invalid="false" placeholder="Subject">
                        </span>
                      </div>
                      <div class="uk-width-1-1 uk-width-small-1-2 uk-width-medium-3-5 uk-width-large-3-5">
                        <span class="wpcf7-form-control-wrap your-message">
                          <textarea name="your-message" cols="40" rows="10" class="tm-touch-message uk-margin-bottom" aria-required="true" aria-invalid="false" placeholder="Message"></textarea>
                        </span>
                        <div class="uk-grid uk-grid-medium" data-uk-grid-margin="">
                          <div class="uk-width-1-1 uk-width-small-1-1 uk-width-medium-1-3 uk-push-2-3">
                            <input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit tm-touch-button uk-button uk-button-primary">
                            <img class="ajax-loader" src="http://w-m-valeo.torbara.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;">
                          </div>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<%= content_for(:dynamic_javascripts) do %>
<script>
  displayGoogleMap("https://maps.google.com/maps?hl=en&q=Agent Formula 8400 W Sahara Ave, Las Vegas, NV. 89117&ie=UTF8&t=roadmap&z=15&iwloc=B&output=embed", 200)
</script>
<% end %>

app/views/pages/testimonials.html.erb
<%= content_for(:title, "Testimonials | AgentFormula.com") %>
<h1>Testimonials</h1>

app/views/pages/websites.html.erb
<%= content_for(:title, "Websites | AgentFormula.com") %>
<h1>Websites</h1>

app/views/shared/_breadcrumb_bar.html.erb
<!-- Breadcrumbs -->
<div id='breadcrumbs'>
  <div class='uk-container uk-container-center'>
    <div class='uk-grid'>
      <div class='uk-width-medium-4-5 uk-width-large-5-6 uk-hidden-small'>
        <ul class='breadcrumbs uk-breadcrumbs uk-subnav uk-subnav-line'>
          <li itemscope itemtype='http://data-vocabulary.org/Breadcrumb'>
            <a href="<%= root_url %>" itemprop='url'>
              <span itemprop='title'>Home</span>
            </a>
          </li>
          <% if !params[:page].blank? %>
          <li>
            <strong>Websites</strong>
          </li>
          <li>
            <strong>For Real Estate Agents</strong>
          </li>
          <li>
            <strong><%= params[:page] %></strong>
          </li>
          <% else %>
          <li>
            <strong><%= yield(:breadcrumb) || params[:action] %></strong>
          </li>
          <% end %>
        </ul>
      </div>
      <div class='uk-navbar-flip uk-width-medium-1-5 uk-width-large-1-6 uk-hidden-small'>
        <a href='tel:1-702-990-0480' class='uk-align-right uk-margin-right'><i class='uk-icon-phone'></i> (702) 990-0480</a>
      </div>
    </div>
  </div>
</div>
<!-- /Breadcrumbs -->

app/views/shared/_mobile_navbar.html.erb
<div id='offcanvas' class='uk-offcanvas' aria-hidden='true'>
  <div class='uk-offcanvas-bar uk-offcanvas-bar-show'>
    <ul class='uk-nav uk-nav-offcanvas' data-uk-nav>
      <li>
        <a class='uk-h4' href="<%= agent_page_path(:features) %>">
          <i class='uk-icon-trophy'></i> Website Features
        </a>
      </li>
      <li>
        <a class='uk-h4' href="<%= agent_page_path(:testimonials) %>">
          <i class='uk-icon-star'></i> Testimonials
        </a>
      </li>
      <li>
        <a class='uk-h4' href="<%= agent_page_path(:training) %>">
          <i class='uk-icon-clock-o'></i> Training Classes
        </a>
      </li>
      <li class='uk-nav-header'>For Real Estate Agents</li>
      <li>
        <%= link_to('Content Management', agent_page_path(:cms)) %>
      </li>
      <li>
        <%= link_to('MLS IDX', agent_page_path(:idx)) %>
      </li>
      <li>
        <%= link_to('30+ HD Videos', agent_page_path(:videos)) %>
      </li>
      <li>
        <%= link_to('City Centric Content', agent_page_path(:content)) %>
      </li>
      <li>
        <%= link_to('Lead Capture', agent_page_path(:'lead-capture')) %>
      </li>
      <li>
        <%= link_to('Lead Management', agent_page_path(:crm)) %>
      </li>
      <li>
        <%= link_to('Drip Marketing', agent_page_path(:'drip-marketing')) %>
      </li>
      <li>
        <%= link_to('Social Media Publishing', agent_page_path(:'social-media')) %>
      </li>
      <li>
        <%= link_to('Blogging Platform', agent_page_path(:blog)) %>
      </li>
      <li>
        <%= link_to('Live Support', agent_page_path(:support)) %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class='nav-placeholder'>
  <div id='nav'>
    <a href='#offcanvas' class='uk-navbar-toggle uk-hidden-large' data-uk-offcanvas></a>
    <div class='uk-container uk-container-center'>
      <%= render 'shared/mobile_navbar' %>
      <div class='uk-navbar-brand' itemscope itemtype='http://schema.org/Product'>
        <a itemprop='url' href="<%= root_url %>" title='AgentFormula.com'>
          <!--AgentFormula.com https://s3-us-west-1.amazonaws.com/sales.agentformula.com/agentformula-logo-484x77.png-->
          <%= image_tag('signup-banner.png', itemprop: 'logo', alt: 'Agent Formula | Building Real Estate Agent Websites', width: '242', height: '39') %>
        </a>
      </div>
      <ul class='uk-navbar-nav uk-margin-large-left uk-hidden-medium uk-hidden-small'>
        <li class='uk-parent' data-uk-dropdown aria-haspopup='true' aria-expanded='false'>
          <a href="/">
            <i class='uk-icon-bars'></i>
            For Real Estate Agents
          </a>
          <div class='uk-dropdown uk-dropdown-navbar uk-dropdown-width-4'>
            <div class='uk-grid uk-dropdown-grid'>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <a href="<%= agent_page_path(:features) %>" class='uk-h4'>
                      <i class='uk-icon-trophy'></i>
                      System Features
                    </a>
                  </li>
                  <li>
                    <a href="<%= testimonials_path %>" class='uk-h4'>
                      <i class='uk-icon-star'></i>
                      Testimonials
                    </a>
                  </li>
                  <li>
                    <a href="<%= agent_page_path(:training) %>" class='uk-h4'>
                      <i class='uk-icon-clock-o'></i>
                      Training Classes
                    </a>
                  </li>
                  <li>
                    <a href="<%= agent_page_path(:training) %>" class='uk-h4'>
                      <i class='uk-icon-life-ring'></i>
                      Live Support
                    </a>
                  </li>
                </ul>
              </div>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <%= link_to('Lead Capture', agent_page_path(:'lead-capture')) %>
                  </li>
                  <li>
                    <%= link_to('Lead Management', agent_page_path(:crm)) %>
                  </li>
                  <li>
                    <%= link_to('Email Drip Marketing', agent_page_path(:'drip-marketing')) %>
                  </li>
                  <li>
                    <%= link_to('Social Media Publishing', agent_page_path(:'social-media')) %>
                  </li>
                </ul>
              </div>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <%= link_to('Sticky Content', agent_page_path(:content)) %>
                  </li>
                  <li>
                    <%= link_to('MLS IDX Search', agent_page_path(:idx)) %>
                  </li>
                  <li>
                    <%= link_to('HQ Area Videos', agent_page_path(:videos)) %>
                  </li>
                  <li>
                    <%= link_to('Build Custom Webpages', agent_page_path(:cms)) %>
                  </li>
                </ul>
              </div>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <%= link_to('Blogging Platform', blogs_path) %>
                  </li>
                  <li></li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li class='uk-parent' data-uk-dropdown aria-haspopup='true' aria-expanded='false'>
          <a href="/">
            <i class='uk-icon-bars'></i>
            For Brokers
          </a>
          <div class='uk-dropdown uk-dropdown-navbar uk-dropdown-width-4'>
            <div class='uk-grid uk-dropdown-grid'>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <a href="<%= agent_page_path(:features) %>" class='uk-h4'>
                      <i class='uk-icon-trophy'></i>
                      System Features
                    </a>
                  </li>
                  <li>
                    <a href="<%= testimonials_path %>" class='uk-h4'>
                      <i class='uk-icon-star'></i>
                      Testimonials
                    </a>
                  </li>
                  <li>
                    <a href="<%= agent_page_path(:training) %>" class='uk-h4'>
                      <i class='uk-icon-clock-o'></i>
                      Training Classes
                    </a>
                  </li>
                </ul>
              </div>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <%= link_to('Lead Capture', agent_page_path(:'lead-capture')) %>
                  </li>
                  <li>
                    <%= link_to('Lead Management', agent_page_path(:crm)) %>
                  </li>
                  <li>
                    <%= link_to('Drip Marketing', agent_page_path(:'drip-marketing')) %>
                  </li>
                  <li>
                    <%= link_to('Social Media Publishing', agent_page_path(:'social-media')) %>
                  </li>
                </ul>
              </div>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <%= link_to('Sticky Content', agent_page_path(:cms)) %>
                  </li>
                  <li>
                    <%= link_to('MLS IDX', agent_page_path(:idx)) %>
                  </li>
                  <li>
                    <%= link_to('30+ HD Videos', agent_page_path(:videos)) %>
                  </li>
                  <li>
                    <%= link_to('City Centric Content', agent_page_path(:content)) %>
                  </li>
                </ul>
              </div>
              <div class='uk-width-1-4'>
                <ul class='uk-nav uk-nav-dropdown uk-panel'>
                  <li>
                    <%= link_to('Blogging Platform', agent_page_path(:blog)) %>
                  </li>
                  <li>
                    <%= link_to('Support Included', agent_page_path(:support)) %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li>
          <a href="<%= contact_us_path %>" rel='nofollow'>Contact Us</a>
        </li>
      </ul>
      <div class='uk-navbar-flip uk-hidden-small'>
        <ul class='uk-navbar-nav'>
          <li>
            <%= link_to('Login', "/submit", rel: 'nofollow') %>
          </li>
          <li>
            <%= link_to('Sign Up', new_customer_registration_path, rel: 'nofollow') %>
          </li>
          <li></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<!-- /Navbar -->